
items = [
  'some rope',
  'a sword',
  'a bucket',
  'a torch',
  'a candle',
  'an axe',
  'matches',
  'coins',
  'a dead fish',
  'dynamite',
  'a lead weight',
  'a magnet',
  'some paper',
  'a spring',
  'a mirror',
  'a pen',
  'a bottle of ketchup',
  'some grapes',
  'a tomato',
  'some keys',
  'a needle',
  'a spade',
  'a toothbrush',
  'a box',
  'some peanuts',
  'a crash helmet',
  'a mirror',
  'thermal pants',
  'a clock',
  'a thermometer',
  'some cutlery',
  'camping equipment',
  'a bag',
  'a bottle of vodka',
  'some party balloons',
  'a porkpie',
  'some chocolate biscuits',
  'a mobile phone',
  'a book',
  'an ipod',
  'some headphones',
  'the statue of liberty',
  'a guitar',
  'toilet paper',
]